name: 测试Docker拉取并导出产物
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取镜像
        run: docker pull swr.cn-east-2.myhuaweicloud.com/qiaixing/coderunner:v1

      - name: 导出镜像为文件
        run: docker save -o coderunner.tar swr.cn-east-2.myhuaweicloud.com/qiaixing/coderunner:v1

      - name: 上传为可下载产物
        uses: actions/upload-artifact@v4
        with:
          name: coderunner-image
          path: coderunner.tar